spring:
  application:
    name: test-service
  config:
    import: optional:configserver:http://localhost:7021
server:
  port: 7031

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka